apiVersion: apps/v1
kind: Deployment
metadata:
    name: mongodb-test
spec:
    selector:
        matchLabels:
            app: mongodb
    replicas: 1
    template:
        metadata:
            labels:
                app: mongodb
        spec:
            containers:
                - name: mongodb
                  imagePullPolicy: Never
                  image: mongodb:test
                  resources:
                      limits:
                          cpu: 50m
                          memory: 100Mi
                      requests:
                          cpu: 25m
                          memory: 10Mi
                  ports:
                      - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
    name: mongodb-service
spec:
    type: NodePort
    selector:
        app: mongodb
    ports:
        - port: 27017
          targetPort: 27017
