apiVersion: apps/v1
kind: Deployment
metadata:
    name: test_env
spec:
    selector:
        matchLabels:
            app: rideshare_test
    replicas: 1
    template:
        metadata:
            labels:
                app: rideshare_test
        spec:
            containers:
                - name: trip-server
                  imagePullPolicy: Always
                  image: trip-server:latest
                  resources:
                      limits:
                          cpu: 50m
                          memory: 100Mi
                      requests:
                          cpu: 25m
                          memory: 10Mi
                  command: ["python3"]
                  ports:
                      - containerPort: 8080

                - name: mongodb
                  imagePullPolicy: Always
                  image: mongodb:latest
                  resources:
                      limits:
                          cpu: 50m
                          memory: 100Mi
                      requests:
                          cpu: 25m
                          memory: 10Mi
                  ports:
                      - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
    name: example
spec:
    type: NodePort
    selector:
        app: example
    ports:
        - port: 8080
          targetPort: 8080
