apiVersion: apps/v1
kind: Deployment
metadata:
    name: trip-server-test
spec:
    selector:
        matchLabels:
            app: trip-server
    replicas: 1
    template:
        metadata:
            labels:
                app: trip-server
        spec:
            containers:
                - name: trip-server
                  imagePullPolicy: Never
                  image: trip-server:test
                  resources:
                      limits:
                          cpu: 50m
                          memory: 100Mi
                      requests:
                          cpu: 25m
                          memory: 10Mi
                  ports:
                      - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
    name: trip-server-service
spec:
    type: NodePort
    selector:
        app: trip-server
    ports:
        - name: trip-server
          protocol: TCP
          port: 8080
          targetPort: 8080
          nodeport: 38080
