protoc:
   protoc --go_out=./proto --go-grpc_out=./proto proto/*.proto

run:
	go run cmd/main.go -log-level debug -start "***REMOVED*** shallowford rd, roswell,ga" -end "homedepot 30075" -driver "brusters woodstock rd, roswell,ga"

