services:
  mongo:
    image: rideshare-mongodb:latest
    build:
      context: .
    ports:
      - 27017:27017
    container_name: rideshare_mongo
    volumes:
      - mongo_data_db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=Password1!
    networks:
      - rideshare-network

networks:
  rideshare-network:
    ipam:
      driver: default

volumes:
  mongo_data_db:
