
name: Build trip_server

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          load: true
          tags: build-trip-server:latest
          context: ./docker/build
          file: ./docker/build/build_trip_server.dockerfile

      - name: Build trip_server executable
        uses: addnab/docker-run-action@v3
        with:
            image: build-trip-server:latest
            options: --rm -v ${{ github.workspace }}:/app -w /app
            run: |
              make build_trip_server

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: trip_server_binary
          # path: ${{ github.workspace }}
          path: ./trip_server
